# run
# docker-compose -f compose_compile_snowboy_all.yml up
# result will be placed in /tmp/snowboy

version: '2.2'
services:
  python27:
    build:
      context: .
      dockerfile: compile_snowboy_python27.dockerfile
    volumes:
      - /tmp/snowboy/python27:/data
  python34:
    build:
      context: .
      dockerfile: compile_snowboy_python34.dockerfile
    volumes:
      - /tmp/snowboy/python34:/data
  python35:
    build:
      context: .
      dockerfile: compile_snowboy_python35.dockerfile
    volumes:
      - /tmp/snowboy/python35:/data
  python36:
    build:
      context: .
      dockerfile: compile_snowboy_python36.dockerfile
    volumes:
      - /tmp/snowboy/python36:/data
  python37:
    build:
      context: .
      dockerfile: compile_snowboy_python37.dockerfile
    volumes:
      - /tmp/snowboy/python37:/data
